version: develop-{build}

branches:
  only:
  - 0.2.3

environment:
  global:
    MINICONDA: "C:\\tools\\Miniconda"

  matrix:
    - PYTHON_VERSION: 2.7
    # - PYTHON_VERSION: 3.4

install:
  # Install miniconda using a powershell script.
  - "choco install -y miniconda"
  - "SET PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"

  # Install the build and runtime dependencies of the project.
  - "conda config --set always_yes yes --set changeps1 no"
  - "conda update -q conda"
  - "conda info -a"
  - "conda create -q -n test-environment python=%PYTHON_VERSION%"
  - "activate test-environment"

  # Check that we have the expected version of Python
  - "python --version"

  # Install dependencies
  - conda config --add channels hydroffice
  - conda config --add channels SciTools
  - conda config --add channels IOOS
  
  - conda install -q numpy matplotlib h5py lxml pytest pydap wxpython
  
  - pip install --no-dependencies hydroffice.bag
  - pip install --no-dependencies hdf_compass

build:
  - python setup.py install

after_build:
   # freezing stuff
  - pip install pyinstaller
  - pyinstaller --clean -y BAGExplorer.1file.spec
  
test_script:
  - "py.test"